create database Discapacidad
go

use Discapacidad
go

CREATE TABLE DIM_PROVINCIA (
    ID_PROVINCIA INT IDENTITY(1,1) PRIMARY KEY,
    PROVINCIA VARCHAR(50)
);
go

CREATE TABLE DIM_DISTRITO (
    ID_DISTRITO INT IDENTITY(1,1) PRIMARY KEY,
    DISTRITO VARCHAR(50)
);
go

CREATE TABLE DIM_DISCAPACIDADES (
    ID_DISCAPACIDADES INT IDENTITY(1,1) PRIMARY KEY,
    DISCAPACIDADES VARCHAR(200)
);
go

CREATE TABLE DIM_AYUDA_BIOMECANICAS (
    ID_AYUDA_BIOMECANICAS INT IDENTITY(1,1) PRIMARY KEY,
    AYUDA_BIOMECANICAS VARCHAR(200)
);
go

CREATE TABLE DIM_METODO_COMUNICACION (
    ID_METODO_COMUNICACION INT IDENTITY(1,1) PRIMARY KEY,
    METODO_COMUNICACION VARCHAR(200)
);
go

CREATE TABLE DIM_BARRERA_DISCAPACIDAD (
    ID_BARRERA_DISCAPACIDAD INT IDENTITY(1,1) PRIMARY KEY,
    BARRERA_DISCAPACIDAD VARCHAR(200)
);
go

CREATE TABLE DIM_LUGAR_BARRERA (
    ID_LUGAR_BARRERA INT IDENTITY(1,1) PRIMARY KEY,
    LUGAR_BARRERA VARCHAR(200)
);
go

CREATE TABLE DIM_GRADO_ACADEMICO (
    ID_GRADO_ACADEMICO INT IDENTITY(1,1) PRIMARY KEY,
    GRADO_ACADEMICO VARCHAR(100)
);
go

CREATE TABLE DIM_INSTITUCIONES (
    ID_INSTITUCIONES INT IDENTITY(1,1) PRIMARY KEY,
    INSTITUCIONES VARCHAR(255)
);
go

CREATE TABLE DIM_CARRERA (
    ID_CARRERA INT IDENTITY(1,1) PRIMARY KEY,
    CARRERA VARCHAR(100)
);
go

CREATE TABLE DIM_VIVIENDA (
    ID_VIVIENDA INT IDENTITY(1,1) PRIMARY KEY,
    VIVIENDA VARCHAR(20)
);
go

CREATE TABLE DIM_TIPO_VIVIENDA (
    ID_TIPO_VIVIENDA INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_VIVIENDA VARCHAR(30)
);
go

CREATE TABLE FACT_PERSONA_DISCAPACITADO (
    ID_PERSONA_DISCAPACITADO VARCHAR(50),
    ID_PROVINCIA INT,
    ID_DISTRITO INT,
    ID_VIVIENDA INT,
    ID_TIPO_VIVIENDA INT,
	ID_GRADO_ACADEMICO INT,
    ID_CARRERA INT,
    ID_INSTITUCIONES INT,
    ID_DISCAPACIDADES INT,
    ID_BARRERA_DISCAPACIDAD INT,
    ID_LUGAR_BARRERA INT,
    ID_AYUDA_BIOMECANICAS INT,
    ID_METODO_COMUNICACION INT,
	SEXO VARCHAR(15),
    ESTADO_CIVIL VARCHAR(15),
	MIEMBROS_DE_FAMILIA VARCHAR(15),
	SITUACION_LABORAL VARCHAR(15),
    INGRESO_MENSUAL VARCHAR(30),
    CALIFICACION_SISFOH VARCHAR(30),
    TIENE_OFICIO_CAPACITACION VARCHAR(15),
    TIENE_CERTIFICADO VARCHAR(15),
	SEGUROS VARCHAR(100),
    CARNET_DE_DISCAPACIDAD VARCHAR(15),
    BENEFICIOS_CONADIS VARCHAR(15)
);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_PROVINCIA 
FOREIGN KEY (ID_PROVINCIA) REFERENCES DIM_PROVINCIA(ID_PROVINCIA);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_DISTRITO 
FOREIGN KEY (ID_DISTRITO) REFERENCES DIM_DISTRITO(ID_DISTRITO);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_VIVIENDA 
FOREIGN KEY (ID_VIVIENDA) REFERENCES DIM_VIVIENDA(ID_VIVIENDA);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_TIPO_VIVIENDA 
FOREIGN KEY (ID_TIPO_VIVIENDA) REFERENCES DIM_TIPO_VIVIENDA(ID_TIPO_VIVIENDA);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_DISCAPACIDADES 
FOREIGN KEY (ID_DISCAPACIDADES) REFERENCES DIM_DISCAPACIDADES(ID_DISCAPACIDADES);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_BARRERA_DISCA
FOREIGN KEY (ID_BARRERA_DISCAPACIDAD) REFERENCES DIM_BARRERA_DISCAPACIDAD(ID_BARRERA_DISCAPACIDAD);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_LUGAR_BARRERA 
FOREIGN KEY (ID_LUGAR_BARRERA) REFERENCES DIM_LUGAR_BARRERA(ID_LUGAR_BARRERA);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_AYUDA_BIOMEC 
FOREIGN KEY (ID_AYUDA_BIOMECANICAS) REFERENCES DIM_AYUDA_BIOMECANICAS(ID_AYUDA_BIOMECANICAS);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_METODO_COM 
FOREIGN KEY (ID_METODO_COMUNICACION) REFERENCES DIM_METODO_COMUNICACION(ID_METODO_COMUNICACION);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_GRADO_ACAD 
FOREIGN KEY (ID_GRADO_ACADEMICO) REFERENCES DIM_GRADO_ACADEMICO(ID_GRADO_ACADEMICO);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_CARRERA 
FOREIGN KEY (ID_CARRERA) REFERENCES DIM_CARRERA(ID_CARRERA);

ALTER TABLE FACT_PERSONA_DISCAPACITADO
ADD CONSTRAINT FK_FACT_INSTITUCIONES
FOREIGN KEY (ID_INSTITUCIONES) REFERENCES DIM_INSTITUCIONES(ID_INSTITUCIONES);



select * from FACT_PERSONA_DISCAPACITADO

select * from DIM_VIVIENDA
